nb_threads = 2
update_templates = true

# If the admins sections is present, the admins will be read in the cosmogony file.
# Otherwise, admins will be fetched  from elasticsearch
# [admins]
# cosmogony_file = "/home/pascal/mimirsbrunn/cosmogony-europe.jsonl.gz"
# configuration for reading the cosmogony file
# french_id_retrocompatibility = true
# langs = [ "fr" ]

[container]
  name = "addr"
  dataset = "fr"
  visibility = "public"
  number_of_shards = 1
  number_of_replicas = 0

[coordinates]
  id_precision = 6
