mode = "default"
nb_threads = 2
http_cache_duration = 3600
# Timeout in milliseconds on client calls to Elasticsearch for /autocomplete endpoint
autocomplete_timeout = 2000
# Timeout in milliseconds on client calls to Elasticsearch for /reverse endpoint
reverse_timeout = 200
# Timeout in milliseconds on client calls to Elasticsearch for /features endpoint
features_timeout = 200

[service]
host = "0.0.0.0"
port = "5000"
content_length_limit = 32768 # 32 x 1024
