langs = [ "fr" ]
nb_threads = 2
french_id_retrocompatibility = true
update_templates = true

[container]
  name = "admin"
  dataset = "fr"
  visibility = "public"
  number_of_shards = 1
  number_of_replicas = 0
